services:
  nfs-server:
    image: ${IMAGE_NAME:-pedroetb/nfs-server}:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-nfs-server}
    environment:
      NFS_PORT:
      NFS_VERSION:
      NFS_DISABLE_VERSION_3: 1
      NFS_SERVER_THREAD_COUNT:
      NFS_EXPORT_0: ${NFS_ROOT_PATH} ${NFS_ROOT_ADDR}(${NFS_ROOT_OPTS})
    network_mode: host
    volumes:
      - data-vol:${NFS_ROOT_PATH}
      - /lib/modules:/lib/modules:ro
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    security_opt:
      - apparmor=${APPARMOR_PROFILE}
    restart: always
    stop_grace_period: ${STOP_GRACE_PERIOD:-1m}
    cpus: '${CPUS:-2}'
    mem_limit: ${MEM_LIMIT:-512M}
    mem_reservation: ${MEM_RESERVATION:-256M}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-nfs-data-vol}
    driver: ${VOL_DRIVER:-local}
