version: '3.7'

services:
  nfs-server:
    image: ${IMAGE_NAME:-erichough/nfs-server}:${IMAGE_TAG:-latest}
    container_name: nfs-server
    environment:
      NFS_PORT:
      NFS_VERSION:
      NFS_DISABLE_VERSION_3: 1
      NFS_EXPORT_0: ${NFS_ROOT_PATH} ${NFS_ROOT_ADDR}(${NFS_ROOT_OPTS})
    ports:
      - target: ${NFS_PORT}
        published: ${NFS_EXPOSED_PORT:-2049}
        protocol: tcp
        mode: ${NFS_PORT_MODE:-host}
    volumes:
      - data-vol:${NFS_ROOT_PATH}
      - /lib/modules:/lib/modules:ro
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    restart: always

volumes:
  data-vol:
    name: ${NFS_SERVER_DATA_VOL_NAME:-nfs-data-vol}
